__name__ = "Shortcuts"
__description__ = "Создает ярлыки на настройки плагинов, их саб-фрагменты (подстраницы), переключатели и диплинки"
__version__ = "1.3"
__id__ = "shortcuts"
__author__ = "@nonPlugins"
__icon__ = "feature_plugins/3"
__min_version__ = "12.1.1"
